import "server-only";
import { NextResponse } from "next/server";
import { Document,Page,StyleSheet,Text,View,renderToBuffer } from "@react-pdf/renderer";
import ExcelJS from "exceljs";
import { createAdminClient } from "@/server/supabase/clients";
import { AppError, mapDatabaseError } from "@/server/errors/app-error";

type Row={customer:string;tracking:string;weight:string;fee:number};
const styles=StyleSheet.create({page:{padding:28,fontFamily:"Helvetica",fontSize:8},title:{fontSize:17,fontWeight:700,marginBottom:4},subtitle:{fontSize:9,color:"#555",marginBottom:16},header:{display:"flex",flexDirection:"row",backgroundColor:"#173f35",color:"#fff",padding:6},row:{display:"flex",flexDirection:"row",padding:5,borderBottom:"1 solid #ddd"},number:{width:"6%"},customer:{width:"24%"},tracking:{width:"34%"},weight:{width:"15%"},fee:{width:"21%",textAlign:"right"},total:{display:"flex",flexDirection:"row",justifyContent:"flex-end",padding:6,backgroundColor:"#eef5f2",fontWeight:700}});
function rupiah(value:number){return `Rp${new Intl.NumberFormat("id-ID").format(value)}`}
function ClosingPdf({code,date,rows}:{code:string;date:string;rows:Row[]}){const groups=Map.groupBy(rows,row=>row.customer);return <Document><Page size="A4" style={styles.page}><Text style={styles.title}>JASTIPin — {code}</Text><Text style={styles.subtitle}>Tanggal closing: {date}</Text><View style={styles.header}><Text style={styles.number}>NO</Text><Text style={styles.customer}>CUSTOMER</Text><Text style={styles.tracking}>TRACKING NUMBER</Text><Text style={styles.weight}>WEIGHT</Text><Text style={styles.fee}>SHIPPING FEE</Text></View>{[...groups.entries()].map(([customer,items])=><View key={customer} wrap={false}>{items.map((row,index)=><View style={styles.row} key={`${row.tracking}-${index}`}><Text style={styles.number}>{index+1}</Text><Text style={styles.customer}>{row.customer}</Text><Text style={styles.tracking}>{row.tracking}</Text><Text style={styles.weight}>{row.weight} kg</Text><Text style={styles.fee}>{rupiah(row.fee)}</Text></View>)}<View style={styles.total}><Text>Total {customer}: {rupiah(items.reduce((sum,row)=>sum+row.fee,0))}</Text></View></View>)}</Page></Document>}

export async function exportClosingDocument(id:string,format:string){
  if(!["pdf","xlsx","csv"].includes(format))throw new AppError("VALIDATION_ERROR","Format export harus pdf, xlsx, atau csv.");
  const result=await createAdminClient().from("closings").select("code,closing_date,closing_packages(shipping_fee_snapshot_idr,chargeable_weight_snapshot_kg,packages(tracking_number,customers(name)))").eq("id",id).single();if(result.error)mapDatabaseError(result.error);
  const closing=result.data as unknown as {code:string;closing_date:string;closing_packages:{shipping_fee_snapshot_idr:string;chargeable_weight_snapshot_kg:string;packages:{tracking_number:string;customers:{name:string}}}[]};
  const rows:Row[]=closing.closing_packages.map(item=>({customer:item.packages.customers.name,tracking:item.packages.tracking_number,weight:item.chargeable_weight_snapshot_kg,fee:Number(item.shipping_fee_snapshot_idr)}));
  const groups=Map.groupBy(rows,row=>row.customer);
  if(format==="pdf"){const output=await renderToBuffer(<ClosingPdf code={closing.code} date={closing.closing_date} rows={rows}/>);return new NextResponse(new Uint8Array(output),{headers:{"content-type":"application/pdf","content-disposition":`attachment; filename="${closing.code}.pdf"`}})}
  if(format==="xlsx"){const workbook=new ExcelJS.Workbook();const sheet=workbook.addWorksheet("Closing");sheet.columns=[{header:"NO",key:"no",width:8},{header:"CUSTOMER",key:"customer",width:30},{header:"TRACKING NUMBER",key:"tracking",width:30},{header:"WEIGHT",key:"weight",width:14},{header:"SHIPPING FEE",key:"fee",width:18}];let number=1;for(const [customer,items] of groups){for(const row of items)sheet.addRow({no:number++,customer,tracking:row.tracking,weight:Number(row.weight),fee:row.fee});const total=sheet.addRow({customer:`TOTAL ${customer}`,fee:items.reduce((sum,row)=>sum+row.fee,0)});total.font={bold:true};total.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFE8F3EF"}}}sheet.getColumn("fee").numFmt='"Rp"#,##0';const output=await workbook.xlsx.writeBuffer();return new NextResponse(new Uint8Array(output),{headers:{"content-type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename="${closing.code}.xlsx"`}})}
  const lines=["NO,CUSTOMER,TRACKING NUMBER,WEIGHT,SHIPPING FEE"];let number=1;for(const [customer,items] of groups){for(const row of items)lines.push([number++,customer,row.tracking,row.weight,row.fee].map(value=>`"${String(value).replaceAll('"','""')}"`).join(","));lines.push(["",`TOTAL ${customer}`,"","",items.reduce((sum,row)=>sum+row.fee,0)].map(value=>`"${value}"`).join(","))}return new NextResponse(`\uFEFF${lines.join("\n")}`,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename="${closing.code}.csv"`}});
}

